### ISSUE TITLE
Cannot save PodioItem

### ISSUE THREAD

**Issue by kringkaste** [podio/podio-php#116]
I have the same error as in issue #96. I created a simple app in Podio with only one text field. Using the latest podio-php version and with the following code I can reproduce the "must be object or must be object" error:

```
require_once 'vendor/podio/podio-php/PodioAPI.php';

$clientId = '***';
$clientSecret = '***';
$appId = '***';
$appToken = '***';

Podio::setup($clientId, $clientSecret);
Podio::authenticate_with_app($appId, $appToken);
Podio::set_debug(true);

$fields = new PodioFieldCollection([
	new PodioTextItemField(['external_id' => 'test-field', 'values' => 'test'])
]);

$item = new PodioItem([
	'app' => new PodioApp(intval($appId)),
	'fields' => $fields
]);

try {
	$item->save();
} catch (PodioError $ex) {
	print_r($ex);
}
```

The debug output is:

```
400 POST /item/app/***/
Request body: {"fields":["Test"],"app":{"app_id":***}}
Reponse: {"error_parameters":{},"error_detail":null,"error_propagate":false,"request":{"url":"http:\/\/api.podio.com\/item\/app\/***\/","query_string":"","method":"POST"},"error_description":"Invalid value [\"Test\"] (array): must be object or must be object","error":"invalid_value"}
```

It's a very simple example, but it doesn't work. What did I wrong?

**Comment by Kjaal** [comment]
Same problem.. exact same code..

**Comment by Kjaal** [comment]
Hey man, got it working. here is my code.

`
    public function create()
    {
    	$client_id = '*********';
    	$client_secret = '*****';
    	$app_id = '*****';
    	$app_token = '*******';

    	   Podio::setup($client_id, $client_secret);
		Podio::authenticate_with_app($app_id, $app_token);
		Podio::set_debug(true);

		$fields = new \PodioItemFieldCollection(array(
		  new \PodioTextItemField(array("external_id" => "titel", "values" => "FooBar")),
		));

		$item = new PodioItem(array(
		  'app' => new \PodioApp(intval($app_id)),
		  'fields' => $fields
		));

		$item->save();

		// return new \PodioApp(intval($app_id));
    }
}
`

**Comment by kringkaste** [comment]
My mistake: I used PodioFieldCollection instead of PodioItemFieldCollection.
