### ISSUE TITLE
Podio Filter is not working

### ISSUE THREAD

**Issue by patidarkishor777** [podio/podio-php#147]
Hi, I am using this for item filter

$response = PodioItem::filter( $clientAPPID, array('filters'=>array('146212406'=>array('shashankkumar427@gmail'))),array() );
But I am receiving following error.

![image](https://user-images.githubusercontent.com/32788804/42642943-93ec27e6-8615-11e8-81ee-6608cc82e6ad.png)

My goal is to find a item(Client) by email(Field id = 146212406),

**Comment by carlfredrikhero** [comment]
I don't think you can filter text fields. Check the body of the response. It should state the reason to error.

**Comment by carlfredrikhero** [comment]
Also, I don't think Podio is supporting this repo anymore. 😞

**Comment by patidarkishor777** [comment]
Ohh, Is there any new version of repo available?

**Comment by carlfredrikhero** [comment]
Not that I know of.

**Comment by patidarkishor777** [comment]
Filter working now

$invoice = PodioItem::filter( $invoiceAPPID, array(
	                 'filters'=>array(
	                      '174535856' => $xeroInvoiceNumber
	                  ),
	                 'limit'=>2
	                ),array() 
	            );
