### ISSUE TITLE
PodioNotFoundError on file upload with expired token

### ISSUE THREAD

**Issue by globiweb** [podio/podio-php#57]
When calling PodioFile::upload and the auth token is expired, the call fails and returns an error instead of refreshing the token and performing the action like other API calls.

The error is:
PodioNotFoundError: "No matching operation could be found. Missing parameters: source."
Request URL: http://api.podio.com/file/v2/

Stack Trace: 
#0 /var/www/vhosts/podioflow.com/httpdocs/podio-php-master/lib/Podio.php(240): Podio::request('POST', '/file/v2/', Array)
#1 /var/www/vhosts/podioflow.com/httpdocs/podio-php-master/lib/Podio.php(293): Podio::request('POST', '/file/v2/', Array, Array)
#2 /var/www/vhosts/podioflow.com/httpdocs/podio-php-master/models/PodioFile.php(39): Podio::post('/file/v2/', Array, Array)

**Comment by daviferreira** [comment]
Can you check if this still happens?

**Comment by globiweb** [comment]
I'm using the v3 library. Since the v4 library is not backwards compatible, I can't move to it, so I don't know if this is still an issue or not (it is for me :-))

**Comment by daviferreira** [comment]
Ok, thanks!
