### ISSUE TITLE
Embed field "Invalid value"

### ISSUE THREAD

**Issue by moerg** [podio/podio-php#77]
I've tried to put an URL for item.create with no http, such as "www.website.tld" into a embed field. The API warned me with that message: "Invalid value "www.website-example.ca" (string): must be integer".

I've put that same URL using Podio interface as a normal user can do, the result was valid as expected.

Is there something that I don't understand correctly?

**Comment by haugstrup** [comment]
Embed fields take PodioEmbed objects or embed_id values, not a URL string. See examples at: http://podio.github.io/podio-php/fields/#linkembed-field
