### ISSUE TITLE
Server-side flow authentication example contains bugs

### ISSUE THREAD

**Issue by webtinkering** [podio/podio-php#91]
in the first if the condition in the example is `!isset($_GET['code']) && Podio::is_authenticated()`, this never triggers the log in link, Podio::is_authenticated() results in FALSE when not logged in... it should be: `!isset($_GET['code']) && !Podio::is_authenticated()` (note the exclamation mark).

Also, the finalization Podio::authenticate_with_authorization_code call needs a comme. It is now: `Podio::authenticate_with_authorization_code($_GET['code'] REDIRECT_URI);`, it should be: `Podio::authenticate_with_authorization_code($_GET['code'], REDIRECT_URI);`

Just thought I post it here, took me a while to figure out why copy/pasted code from the docs was throwing errors (the missing comma) and then resulting in a blank screen not doing *anything* (no condition is met when not logged in).

**Comment by daviferreira** [comment]
Hey @webtinkering, want to submit a PR? The docs are on the `gh-pages` branch. Let me know if you need help :)
